### ISSUE TITLE
FS-FIA

### ISSUE THREAD

**Issue by ktoddbrown** [ktoddbrown/SoilDRaH#4]
- [x] Download Forest service FIA database
- [x] Annotate database
- [x] Shoestring data

**Comment by ursapillay** [comment]
## TODO after bd5b15aa14f23f07c00f447462ad5676d3af6ec2
**readFIA.R function**
- [ ] annotate remaining datasets
- [ ] filter datasets for only those with associated soil data

**fia.Rmd vignette**
- [ ] cast numerical columns using regex, cast categorical data as factors
- [ ] group plots, add scatterplots/violin plots
- [ ] build out text narrative

**Comment by ktoddbrown** [comment]
Needs more comments in the R script and the Rmd Document. #d9d4879 is pretty close here I think.

**Comment by ktoddbrown** [comment]
This branch is ready for a narrative review. Read through this one more time before #11 and then create a pull request and ask for a review from someone not me.

**Comment by ktoddbrown** [comment]
The content was reviewed by K Heckman offline and is considered a complete report. Creating pull request to merge into main.
